title: space2vec
description: The space between machine learning and astronomy

url: //pippinlee.github.io
baseurl:
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   email: p.lee@dessa.com

google_analytics: "UA-70081252-2"
